# Generated by Django 5.2.6 on 2025-09-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevAppUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_mobile', models.CharField(max_length=10, unique=True)),
                ('user_email', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rev_app_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='rev_app.dept')),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
