# Generated by Django 5.2.4 on 2025-07-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('mob', models.CharField(max_length=10)),
                ('reg_on', models.DateTimeField()),
            ],
        ),
    ]
