# Generated by Django 5.2.4 on 2025-07-31 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash_app', '0002_remove_users_reg_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reg_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 31, 9, 8, 27, 2000)),
        ),
    ]
