# Generated by Django 5.2.5 on 2025-08-07 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USERS',
            new_name='USERS_DATA',
        ),
    ]
