# Generated by Django 5.2.4 on 2025-08-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
