# Generated by Django 5.2.4 on 2025-08-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
