# Generated by Django 5.2.5 on 2025-09-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevAppUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_mobile', models.CharField(max_length=10, unique=True)),
                ('user_email', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rev_app_users',
                'managed': False,
            },
        ),
    ]
