# Generated by Django 5.2.4 on 2025-08-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
