# Generated by Django 5.2.5 on 2025-08-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cookie_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
