# Generated by Django 5.2.5 on 2025-08-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie_user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
