# Generated by Django 5.2.4 on 2025-08-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=15)),
                ('user_mobile', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
