# Generated by Django 5.2.4 on 2025-08-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='user_password',
            field=models.CharField(max_length=255),
        ),
    ]
