# Generated by Django 5.2.4 on 2025-07-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_sample2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletable',
            name='mobile',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
