# Generated by Django 5.2.4 on 2025-08-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_mobile', models.CharField(max_length=10, unique=True)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
