# Generated by Django 5.2.4 on 2025-08-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rev_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_password',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
